server:
  hostUrl: "http://cryptocortex-auth-proxy.deltix"
  port: 4088

oauth2:
  providerName: "auth0"
  providerUri: "https://cryptocortex-dev.us.auth0.com/"
  jwksUriPath: "jwks_uri"
  usernamePath: "name"

scheduled:
  poolSize: 2
