server:
  hostUrl: "http://cryptocortex-auth-proxy.deltix"
  port: 4088

oauth2:
  providerName: "auth0"
  providerUri: "https://signin-stg-admin.tradestation.io"
  usernamePath: "/http://tradestation.com/email"

scheduled:
  poolSize: 2
