server:
  hostUrl: "http://cryptocortex-auth-proxy.deltix"
  port: 4088

oauth2:
  providerUri: "https://kc.staging.deltixhub.io/realms/DIAL"
  clientId: "chatbot-ui"
  clientSecret: "iyJdFnZGxNPBg3XXfOR5Nkbpj42cwPeN"
  jwksUriPath: "jwks_uri"

scheduled:
  poolSize: 2
